# Generated by Django 4.2.6 on 2023-11-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
