# Generated by Django 4.2.6 on 2023-11-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
